apiVersion: v1
kind: Service
metadata:
      name: db
      labels:
        app: postgres
spec:
    type: ClusterIP
    ports:
        - name: postgres
          port: 5432
          protocol: TCP
    selector:
        app: postgres