apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template: 
    metadata:       
      labels:
        app: api
    spec:            
      containers:
      - name: api
        image: developer10/api-futiuber:v2
        ports:
        - containerPort: 8000
        env:
          - name:  NOMEUSER
            value: antonio
          - name: EMAILUSER
            value: antonio@gmail.com
          - name: PWDUSER
            value: antonio